# Generated by Django 3.1.5 on 2021-03-02 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('createList', '0016_auto_20210301_2244'),
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watcherlist',
            name='listID',
        ),
        migrations.AddField(
            model_name='watcherlist',
            name='listID',
            field=models.ManyToManyField(default=1, related_name='lists', to='createList.Listing'),
        ),
        migrations.RemoveField(
            model_name='watcherlist',
            name='userID',
        ),
        migrations.AddField(
            model_name='watcherlist',
            name='userID',
            field=models.ManyToManyField(default=1, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
