# Generated by Django 3.1.5 on 2021-03-02 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0016_auto_20210301_2244'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchlist', '0002_auto_20210302_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watcherlist',
            name='listID',
        ),
        migrations.AddField(
            model_name='watcherlist',
            name='listID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='createList.listing'),
        ),
        migrations.RemoveField(
            model_name='watcherlist',
            name='userID',
        ),
        migrations.AddField(
            model_name='watcherlist',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
