# Generated by Django 3.1.5 on 2021-03-04 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchlist', '0003_auto_20210302_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watcherlist',
            name='userID',
        ),
        migrations.AddField(
            model_name='watcherlist',
            name='addedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watcherlist',
            name='watchedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watchUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
