# Generated by Django 3.1.5 on 2021-02-28 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='code',
            field=models.ForeignKey(default='XXXX', on_delete=django.db.models.deletion.CASCADE, to='createList.category'),
        ),
    ]
