# Generated by Django 3.1.5 on 2021-02-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0002_auto_20210227_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='title_id',
            field=models.IntegerField(auto_created=True, default='1000', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=36),
        ),
    ]
