# Generated by Django 3.1.5 on 2021-02-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0003_auto_20210227_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title_id',
            field=models.AutoField(auto_created=True, default=1000, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
