# Generated by Django 3.1.5 on 2021-02-28 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0006_auto_20210228_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='code',
            new_name='category_name',
        ),
    ]
