# Generated by Django 3.1.5 on 2021-02-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0007_auto_20210228_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
