# Generated by Django 3.1.5 on 2021-02-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0008_auto_20210228_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category_name',
            field=models.ForeignKey(default='XXXX', on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='createList.category'),
        ),
    ]
