# Generated by Django 3.1.5 on 2021-03-02 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0010_auto_20210301_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='userID',
        ),
    ]
