# Generated by Django 3.1.5 on 2021-03-02 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('createList', '0011_remove_listing_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='userID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='createUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
