# Generated by Django 3.1.5 on 2021-03-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0013_auto_20210301_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='createDateTime',
        ),
    ]
