# Generated by Django 3.1.5 on 2021-03-02 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0014_remove_listing_createdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='userID',
        ),
    ]
