# Generated by Django 3.1.5 on 2021-03-02 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('createList', '0015_remove_listing_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='createDateTime',
            field=models.CharField(default='NONE', max_length=60),
        ),
        migrations.AddField(
            model_name='listing',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='createUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category_name',
            field=models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='createList.category'),
        ),
    ]
