# Generated by Django 3.1.5 on 2021-03-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0017_auto_20210302_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.FloatField(),
        ),
    ]
