# Generated by Django 3.1.5 on 2021-03-06 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('createList', '0019_listing_startingbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currBidBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='currBidUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
