# Generated by Django 3.1.5 on 2021-03-10 00:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0021_auto_20210309_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='createDateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 0, 57, 26, 52510, tzinfo=utc)),
        ),
    ]
