# Generated by Django 3.1.5 on 2021-03-10 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0023_auto_20210309_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='createDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
