# Generated by Django 3.1.5 on 2021-03-10 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0025_auto_20210309_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='createDateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 20, 53, 7, 405926)),
        ),
    ]
