# Generated by Django 3.1.5 on 2021-03-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0026_auto_20210309_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='createDateTime',
            field=models.DateTimeField(),
        ),
    ]
