# Generated by Django 3.1.5 on 2021-03-06 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingID', models.CharField(max_length=36)),
                ('amount', models.FloatField()),
                ('datetimeOfBid', models.CharField(default='NONE', max_length=60)),
                ('bidBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bidUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
