# Generated by Django 3.1.5 on 2021-03-06 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createList', '0019_listing_startingbid'),
        ('listings', '0002_auto_20210305_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='listingID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bidUser', to='createList.listing'),
        ),
    ]
