# Generated by Django 3.1.5 on 2021-03-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_hist_lists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hist_lists',
            old_name='createDateTime',
            new_name='closedDateTime',
        ),
    ]
