# Generated by Django 3.1.5 on 2021-03-07 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('createList', '0020_listing_currbidby'),
        ('listings', '0005_auto_20210306_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='listingID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bidList', to='createList.listing'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentMade', models.CharField(max_length=1000)),
                ('datetimeOfComment', models.CharField(default='NONE', max_length=60)),
                ('commentBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentUser', to=settings.AUTH_USER_MODEL)),
                ('listingID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentList', to='createList.listing')),
            ],
        ),
    ]
