# Generated by Django 3.1.5 on 2021-03-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210307_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentMade',
            field=models.CharField(max_length=500),
        ),
    ]
