# Generated by Django 3.1.5 on 2021-03-10 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20210309_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='datetimeOfBid',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetimeOfComment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hist_lists',
            name='closedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
