# Generated by Django 3.1.5 on 2021-03-10 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20210309_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='datetimeOfBid',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 20, 9, 24, 790841)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetimeOfComment',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 20, 9, 24, 794838)),
        ),
        migrations.AlterField(
            model_name='hist_lists',
            name='closedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 20, 9, 24, 795827)),
        ),
    ]
